coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        branches:
          - master
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: off

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "tests"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "coverage"
  - ".next"
  - "dist"
