FROM python:3.9-slim
RUN pip install --no-cache-dir pipx && pipx ensurepath && pipx install skivvy
WORKDIR /app
COPY skivvy/cfg/ ./cfg/
COPY skivvy/examples/ ./examples/
ENTRYPOINT ["skivvy"]
CMD ["run", "cfg/example.json"]
