FROM python:3.9-slim
WORKDIR /app
RUN pip install --no-cache-dir uv && uv install skivvy
COPY skivvy/cfg/ ./cfg/
COPY skivvy/examples/ ./examples/
ENTRYPOINT ["skivvy"]
CMD ["run", "cfg/example.json"]
