name: Build CI image
on:
  push:
  pull_request:
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # for GHCR
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ghcr.io/${{ github.repository }}/skivvy:ci
          
      - uses: docker/login-action@v3
        with:
          registry: hub.docker.com
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ${{ github.repository }}/skivvy:ci

            
