name: CI Workflow
on:
  push:
    branches: [master]

  pull_request:
    types: [opened, reopened]

jobs:
  build-examples:
    uses: ./.github/workflows/docker-build.yml
    with:
      dockerfile: Dockerfile.examples
      primary_tag: examples
      also_latest: false
    secrets: inherit

  build-main:
    uses: ./.github/workflows/docker-build.yml
    with:
      dockerfile: Dockerfile
      primary_tag: dev
      also_latest: false
    secrets: inherit
  zip-examples:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create examples zip
        run: |
          cd examples
          zip -r ../skivvy_examples.zip .
          cd ..
      
      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: skivvy_examples.zip
      
      - name: Commit examples zip to master
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add skivvy_examples.zip
          git diff --staged --quiet || git commit -m "Update skivvy_examples.zip [skip ci]"
          git push
